export const PUBLIC_LIST_FETCH_START = 'PUBLIC_LIST/FETCH_START';
export const PUBLIC_LIST_FETCH_SUCCESS = 'PUBLIC_LIST/FETCH_SUCCESS';
export const PUBLIC_LIST_FETCH_ERROR = 'PUBLIC_LIST/FETCH_ERROR';
