export const ADMIN_CATALOG_FETCH_START = 'ADMIN_CATALOG/FETCH_START';
export const ADMIN_CATALOG_FETCH_SUCCESS = 'ADMIN_CATALOG/FETCH_SUCCESS';
export const ADMIN_CATALOG_FETCH_ERROR = 'ADMIN_CATALOG/FETCH_ERROR';
